parameters:
#    cegeka_flanders_drive.example.class: Cegeka\FlandersDriveBundle\Example

services:
    fd.service.user:
        class: Cegeka\FlandersDriveBundle\Service\UserService
        arguments: [@doctrine.orm.entity_manager]

    fd.service.release:
        class: Cegeka\FlandersDriveBundle\Service\ReleaseService
        arguments: [@doctrine.orm.entity_manager]

    fd.service.excel:
        class: Cegeka\FlandersDriveBundle\Service\ExcelService
        arguments: [@phpexcel]

    fd.service.database:
        class: Cegeka\FlandersDriveBundle\Service\DatabaseService
        arguments: [@doctrine.orm.entity_manager]

    fd.service.filtering:
        class: Cegeka\FlandersDriveBundle\Service\FilteringService
        arguments: [@session]

    fd.service.detail:
        class: Cegeka\FlandersDriveBundle\Service\DetailService
        arguments: [@doctrine.orm.entity_manager]

    fd.service.queryInterface:
            class: Cegeka\FlandersDriveBundle\Service\QueryInterfaceService
            arguments: [@doctrine.orm.entity_manager, @session, @fd.service.filtering]

    fd.service.note:
        class: Cegeka\FlandersDriveBundle\Service\NoteService
        arguments: [@doctrine.orm.entity_manager, @fd.service.search]

    fd.service.solr:
        class: Cegeka\FlandersDriveBundle\Service\SolrService
        arguments: [@solr.client.default, @session, @doctrine.orm.entity_manager, @fd.service.scalingparameters]

    fd.service.search:
        class: Cegeka\FlandersDriveBundle\Service\SearchService
        arguments: [@doctrine.orm.entity_manager]

    fd.service.scalingParameters:
            class: Cegeka\FlandersDriveBundle\Service\ScalingParametersService
            arguments: [@doctrine.orm.entity_manager, @fd.findergenerator]

    fd.findergenerator:
        class: Cegeka\FlandersDriveBundle\Service\FinderGenerator
        arguments: [@doctrine.orm.entity_manager]

    fd.service.graph:
        class: Cegeka\FlandersDriveBundle\Service\GraphService
        arguments: [@doctrine.orm.entity_manager, @fd.service.filtering]

    fd.service.path:
        class: Cegeka\FlandersDriveBundle\Service\PathService

    fd.hydrator.testlab:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\TestlabHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.generalinformation:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\GeneralInformationHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.filestructure:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\FileStructureHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.fullstructure:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\FullStructureHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.company:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\CompanyHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.component:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\ComponentHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.release:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\ReleaseHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.decision:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\DecisionHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.flow:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\FlowHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.glossary:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\GlossaryHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.guideline:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\GuidelineHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.note:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\NoteHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator, @fd.service.user, @fd.service.search]

    fd.hydrator.scaling:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\ScaleHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.step:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\StepHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.symbolabbreviation:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\SymbolAbbreviationHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.recommendation:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\RecommendationHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.material:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\MaterialHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.requirement:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\RequirementHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.role:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\RoleHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.workproduct:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\WorkproductHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    fd.hydrator.user:
        class: Cegeka\FlandersDriveBundle\Service\Hydrator\UserHydrator
        arguments: [@doctrine.orm.entity_manager, @jms_serializer, @fd.findergenerator]

    twig.extension.releaseService:
        class: Cegeka\FlandersDriveBundle\Extensions\FooterExtension
        arguments: [@fd.service.release]
        tags:
            - { name: twig.extension }

    twig.extension.templateService:
            class: Cegeka\FlandersDriveBundle\Extensions\TemplateExtension
            tags:
                - { name: twig.extension }

    login_listener:
        class: Cegeka\FlandersDriveBundle\Listener\LoginListener
        arguments: [@security.context, @session, @fd.findergenerator]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }