services:
    ###############
    # INFORMATION #
    ###############
    fd.admin.component:
        class: Cegeka\FlandersDriveBundle\Admin\ComponentAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Component, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 1. Information, label: Component}

    fd.admin.material:
        class: Cegeka\FlandersDriveBundle\Admin\MaterialAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Material, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 1. Information, label: Material}

    fd.admin.recommendation:
        class: Cegeka\FlandersDriveBundle\Admin\RecommendationAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Recommendation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 1. Information, label: Recommendation}

    fd.admin.requirement:
        class: Cegeka\FlandersDriveBundle\Admin\RequirementAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Requirement, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 1. Information, label: Requirement}

    fd.admin.testlab:
        class: Cegeka\FlandersDriveBundle\Admin\TestlabAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Testlab, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 1. Information, label: Testlab}

    #########
    # ROLES #
    #########
    fd.admin.role:
        class: Cegeka\FlandersDriveBundle\Admin\RoleAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Role, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 2. Roles, label: Role}

    #############
    # DOCUMENTS #
    #############
    fd.admin.guideline:
        class: Cegeka\FlandersDriveBundle\Admin\GuidelineAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Guideline, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 3. Documents, label: Guideline}

    fd.admin.workproduct:
        class: Cegeka\FlandersDriveBundle\Admin\WorkproductAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Workproduct, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 3. Documents, label: Workproduct}

    #############
    # PROCESSES #
    #############
    fd.admin.decision:
        class: Cegeka\FlandersDriveBundle\Admin\DecisionAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Decision, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Decision}

    fd.admin.file_structure:
        class: Cegeka\FlandersDriveBundle\Admin\FileStructureAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\FileStructure, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: File Structure - List}

    fd.admin.file_structure_group:
        class: Cegeka\FlandersDriveBundle\Admin\GroupAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\FileStructure\Group, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: File Structure - Group}

    fd.admin.file_structure_substructure:
        class: Cegeka\FlandersDriveBundle\Admin\SubstructureAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\FileStructure\Substructure, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: File Structure - Substructure}

    fd.admin.step:
        class: Cegeka\FlandersDriveBundle\Admin\StepAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Step, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Step - List}

    fd.admin.paragraph:
        class: Cegeka\FlandersDriveBundle\Admin\ParagraphAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Step\Paragraph, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Step - Paragraph}

    fd.admin.raci:
        class: Cegeka\FlandersDriveBundle\Admin\RaciAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Step\Raci, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Step - Raci}

    fd.admin.step_link_flow:
        class: Cegeka\FlandersDriveBundle\Admin\StepLinkFlowAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Step\LinkFlow, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Step - LinkFlow}

    fd.admin.step_image:
        class: Cegeka\FlandersDriveBundle\Admin\ImageAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Step\Image, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Step - Image}

    fd.admin.flow:
        class: Cegeka\FlandersDriveBundle\Admin\FlowAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Flow, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: List with Flows & Steps & Processes}

    fd.admin.scaling_activity:
        class: Cegeka\FlandersDriveBundle\Admin\ActivityAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\Activity, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Activity}

    fd.admin.scaling_application_type:
        class: Cegeka\FlandersDriveBundle\Admin\ApplicationTypeAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\ApplicationType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Application Type}

    fd.admin.scaling_body:
        class: Cegeka\FlandersDriveBundle\Admin\BodyAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\Body, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Body}

    fd.admin.scaling_process:
        class: Cegeka\FlandersDriveBundle\Admin\ScalingProcessAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\Process, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Process}

    fd.admin.scaling_product_type:
        class: Cegeka\FlandersDriveBundle\Admin\ProductTypeAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\ProductType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - ProductType}

    fd.admin.scaling_region:
        class: Cegeka\FlandersDriveBundle\Admin\RegionAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\Region, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Region}

    fd.admin.scaling_tag:
        class: Cegeka\FlandersDriveBundle\Admin\TagAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Scaling\Tag, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 4. Processes, label: Scaling - Tag}

    #############
    # STANDARDS #
    #############
    fd.admin.general_information:
        class: Cegeka\FlandersDriveBundle\Admin\GeneralInformationAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\GeneralInformation, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 5. Standards, label: General Information}

    fd.admin.symbol_abbreviation_standard:
        class: Cegeka\FlandersDriveBundle\Admin\SymbolAbbreviationStandardAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\SymbolAbbreviation\SymbolAbbreviationStandard, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 5. Standards, label: Sym & Abbr - Value}

    fd.admin.symbol_abbreviation_term:
        class: Cegeka\FlandersDriveBundle\Admin\SymbolAbbreviationTermAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\SymbolAbbreviation\SymbolAbbreviationTerm, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 5. Standards, label: Sym & Abbr - Term}

    fd.admin.glossary_standard:
        class: Cegeka\FlandersDriveBundle\Admin\GlossaryStandardAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Glossary\GlossaryStandard, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 5. Standards, label: Glossary - Value}

    fd.admin.glossary_term:
        class: Cegeka\FlandersDriveBundle\Admin\GlossaryTermAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Glossary\GlossaryTerm, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 5. Standards, label: Glossary - Term}

    ##############
    # USER INPUT #
    ##############
    fd.admin.company:
        class: Cegeka\FlandersDriveBundle\Admin\CompanyAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Company, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 6. User Input, label: Company}

    fd.admin.note:
        class: Cegeka\FlandersDriveBundle\Admin\NoteAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Note, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 6. User Input, label: Note}

    fd.admin.release:
        class: Cegeka\FlandersDriveBundle\Admin\ReleaseAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Release, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: 6. User Input, label: Release}