language: php
php:
- "5.5"
- "5.6"

matrix:
  allow_failures:
    - php: "5.6"

before_script:
  - composer install -n
  - mkdir -p web/uploads
  - mysql -u root -e "CREATE USER 'cegeka'@'localhost' IDENTIFIED BY 'cegeka'"
  - mysql -u root -e "CREATE DATABASE flanders_drive_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON flanders_drive_test.* TO 'cegeka'@'localhost' WITH GRANT OPTION;"
  - php app/console doctrine:migrations:migrate -n --env=test
  - php app/console doctrine:fixtures:load -n --env=test
  - php app/console cache:clear --env=test
script: phpunit -c app
before_deploy:
  - git fetch --unshallow
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: jnLF9lTI4Olcx5JW8JN/t2QnoDKEGYHiAGfMN0niVHhahdVR1lQbB+Q7HHT2chAe5AFw/NnUJPDogrhLQNFiFJWYkS2vTUXPoFB3arI+6MHaZkD+g2vlfxNDgX/MZ3Df1X+SV09FdPrm3ciwgmwSWdyTIT1my8iN7drJ6kHSKvo=
  run:
    - php app/console doctrine:mig:mig -n
    - php app/console doctrine:fixtures:load -n
    - restart
  app: flanders-drive
  on:
    repo: cegeka/flanders-drive
    php: "5.5"
env:
  - SYMFONY__DATABASE__USER=cegeka SYMFONY__DATABASE__PASSWORD=cegeka SYMFONY__DATABASE__HOST=localhost SYMFONY__DATABASE__NAME=flanders_drive