parameters:
    security.acl.permission.map.class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default

    providers:
        in_memory:
            memory:
                users:
                    fld_drive: { password: bfNXPCXp, roles: [ 'ROLE_USER' ] }
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        user:
            pattern: /(.*)
            context: user
            form_login:
                provider: fos_userbundle
                login_path: /profile/login
                use_forward: false
                check_path: /profile/login_check
                failure_path: null
            logout:
                path: /profile/logout
            anonymous: true

        admin:
            pattern: /admin(.*)
            context: user
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login_check
                failure_path: null
            logout:
                path: /admin/logout
            anonymous: true

    access_control:
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/profile/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/, roles: ROLE_USER }

        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }