fd_top_level:
    pattern:    /graph/top-level
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:displayTopLevelGraph }

fd_releases_page:
    pattern:    /releases
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:displayReleaseNotes }

fd_template_browser:
    pattern:    /template-browser
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:documentBrowser }

fd_standards_comparison:
    pattern:    /standards-comparison
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:standardsComparison }

fd_scaling_parameters:
    pattern:    /scaling-parameters
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:scalingParameters }

fd_general_information_list:
    pattern:    /general-information
    defaults:   { _controller: CegekaFlandersDriveBundle:Content:displayListOfGeneralInformationEntries}

fd_symbol_abbreviation_list:
    pattern:    /symbol-abbreviation
    defaults:   { _controller: CegekaFlandersDriveBundle:SymbolAbbreviation:list}

fd_symbol_abbreviation_detail:
    pattern:    /symbol-abbreviation/{id}
    defaults:   { _controller: CegekaFlandersDriveBundle:SymbolAbbreviation:detail}
    
fd_glossary_list:
    pattern:    /glossary
    defaults:   { _controller: CegekaFlandersDriveBundle:Glossary:list}

fd_glossary_detail:
    pattern:    /glossary/{id}
    defaults:   { _controller: CegekaFlandersDriveBundle:Glossary:detail}