fd_detail_testlab:
    pattern: /testlab/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showTestLab }

fd_detail_requirement:
    pattern: /requirement/{id}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showRequirement }

fd_detail_component:
    pattern: /component/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showComponent }

fd_detail_material:
    pattern:  /material/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showMaterial }

fd_detail_recommendation:
    pattern:  /recommendation/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showRecommendation }

fd_detail_flow:
    pattern: /flow/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Default:flow }
    requirements:
        _method: GET

fd_detail_general_information:
    pattern:  /general-information/{flandersId}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showGeneralInformation }

fd_detail_step:
    pattern:  /step/{id}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showStep }

fd_detail_flow_path_only:
    pattern: /flow/
    defaults: { _controller: CegekaFlandersDriveBundle:Default:flow }
    requirements:
        _method: GET

fd_detail_step_path_only:
    pattern:  /step/
    defaults: { _controller: CegekaFlandersDriveBundle:Detail:showStep }

fd_graph_api:
    pattern: /graph
    defaults: { _controller: CegekaFlandersDriveBundle:Graph:index }
    requirements:
        _method: GET

fd_detail_graph_flow:
    pattern: /graph/flow/{id}/show
    defaults: { _controller: CegekaFlandersDriveBundle:Graph:flow }
    requirements:
        _method: GET