fd_export_step:
    pattern:    /step/{identifier}
    defaults:   { _controller: CegekaFlandersDriveBundle:Export:exportStep }

fd_export_flow:
    pattern:    /flow/{identifier}
    defaults:   { _controller: CegekaFlandersDriveBundle:Export:exportFlow }

fd_export_solr_search:
    pattern:    /solr/excel/{searchTerm}
    defaults:   { _controller: CegekaFlandersDriveBundle:Export:exportSolrSearchResults }

fd_export_detail_entry:
    pattern:    /{type}/{identifier}
    defaults:   { _controller: CegekaFlandersDriveBundle:Export:exportSingleEntry }