fd_search_fulltext_handle:
    pattern: /full-text
    defaults: { _controller: CegekaFlandersDriveBundle:Search:handleSearchRequest }

fd_search_fulltext:
    pattern: /full-text/{searchTerm}
    defaults: { _controller: CegekaFlandersDriveBundle:Search:fullText }

fd_search_requirement_testType_tag:
    pattern:  /requirement/test-type/{testType}/tag/{tag}
    defaults: { _controller: CegekaFlandersDriveBundle:Search:searchRequirementByTestTypeAndTag }

fd_search_requirement_testType:
    pattern:  /requirement/test-type/{testType}
    defaults: { _controller: CegekaFlandersDriveBundle:Search:searchRequirementByTestType }

fd_search_general_information:
    pattern:  /general-information/standard/{standard}
    defaults: { _controller: CegekaFlandersDriveBundle:Search:searchGeneralInformationByRequirementStandard }

fd_query_interface:
    pattern:  /query-interface
    defaults: { _controller: CegekaFlandersDriveBundle:Search:queryInterface }