services:
    ###############
    # INFORMATION #
    ###############
    fd.admin.component:
        class: Cegeka\FlandersDriveBundle\Admin\ComponentAdmin
        arguments: [~, Cegeka\FlandersDriveBundle\Entity\Component, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: PinappInfo, label: Component}

